### PR TITLE
Adds query params format to prefill widget

### LINKED ISSUE #979: [Feature]: Lage funksjonalitet for lenke med åpen widget og ferdig utfyllt fordeling
### Contact Details

_No response_

### Description

Til bruk for FEM mm.

### Link to figma / design node

_No response_

### Link to other planning document

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by fellmirr**
Look at the URL and look for a query param
that specifies a payment distribution to prefill
If found, set the distribution cause areas and organizations
to the prefilled values.
Find the corresponding cause area and organization in the state
Use next router to look at the query params
The format of the query param is:
distribution=causeAreaId:share:organizationId-share:organizationId-share
E.g.
1:100:4-50:1-25:12-25
This would set cause area 1 to 100% and distribute the shares
between organizations 4, 1 and 12 with 50%, 25% and 25% respectively

- closes #979 

---

Tested on devices

- [ ] Desktop 💻
- [ ] Mobile 📱

Tests

- [ ] All tests are running ✔️
- [ ] Test are updated 🧪
- [ ] Code Review 👩‍💻
- [ ] QA 👌

Checkpoints

_Check these to flag for a more thurough review, as they could be potentially breaking changes_

- [ ] Packages updated
- [ ] Other infrastructure updated (such as node version or similar)

⏲️ Time spent on CR:

⏲️ Time spent on QA:

### CODE REVIEW

**Comment by fellmirr** [comment]
https://main-site-git-797-prefill-url-effective-altruism-norway.vercel.app/?distribution=1:100:17-100

@karirk @EliseAndresen Prøv den lenken for å se hvordan det blir

**Comment by karirk** [comment]
Det ser ut til å fungere fint det!

ons. 26. juni 2024 kl. 17:40 skrev Håkon Harnes ***@***.***>:

**Comment by EliseAndresen** [comment]
Det ser bra ut!

**Comment by karirk** [comment]
Betyr det at denne tas inn nå? I så fall skal jeg oppdatere teksten til FEM
og sende over i dag.

Mvh Kari

**Pull request merged**
