### PR TITLE
Home page dynamic routing

### LINKED ISSUE #626: [Feature]: Make front page generic
### Contact Details

_No response_

### Description

Remove hardcoded routing for front page and use generic page

- [x] #625 
- [x] #624 
- [x] #623 
- [x] #622 
- [x] #621 
- [x] #620
- [ ] #632

### Link to figma / design node

_No response_

### Link to other planning document

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by adamalfredsson**
Goal is to make front page use generic page model. 

- closes #626 

---

Tested on devices 
- [x] Desktop 💻
- [x] Mobile 📱

Tests  
- [ ] All tests are running ✔️
- [ ] Test are updated 🧪
- [ ] Code Review 👩‍💻
- [ ] QA 👌

⏲️ Time spent on CR:

⏲️ Time spent on QA:

### CODE REVIEW

**Comment by adamalfredsson** [comment]
This should be ready to merge now:

- Adds a generic page
    - Imported SEO and data from custom frontpage
    - Tested against visual regression
- Adds a generic page header layout field
    - Added `layout: 'centered'` for each page header with `centered: true`

One technical regression is that the impact widget no longer is loaded dynamically.

**Comment by adamalfredsson** [comment]
Just confirm that any content edits on the custom frontpage after 21/4 16:00 have also been made to the generic page.

**Comment by fellmirr** [comment]
@adamalfredsson Would you mind checking the conflict with slug? I think you have a better overview than me on the changes. I'll go over and check that there are no missing components from the frontpage, and then merge when ready :)

**Comment by adamalfredsson** [comment]
> @adamalfredsson Assuming this will conflict with the article changes. Which would be better to merge first? In regards to the routing updates.

Good question, I think this one is slightly preferred!

**Comment by fellmirr** [comment]
@adamalfredsson Great, then I'll take this one in once all the tests do their thing

**Review by fellmirr — APPROVED** [review]
Awesome updates :+1:

**Pull request merged**
