### PR TITLE
#570 arsoppgave

### PR DESCRIPTION
**Pull request by fellmirr**
Adds a yearly tax report to the tax tab on "min side".

This PR is a work in progress, the following things are missing:
- [x] Feedback on missing information (tooltip and validation)
- [x] Impact estimate of EAN Giverportal donations
- [ ] e2e tests and mocks for those
- [x] Table for non-deductible donations (crypto f.ex.)

[Figma files are here.](https://www.figma.com/file/rxgTB6O7vQZWbKDSoUY6EU/Min-Side?node-id=1736%3A9367&t=RsuLtOtNRfUpqTpz-1)

Depends on backend changes not merged to master in [this branch](https://github.com/stiftelsen-effekt/effekt-backend/pull/499).

#570 

---

Tested on devices 
- [x] Desktop 💻
- [x] Mobile 📱

Tests  
- [x] All tests are running ✔️
- [x] Test are updated 🧪
- [x] Code Review 👩‍💻
- [x] QA 👌

⏲️ Time spent on CR: 

⏲️ Time spent on QA: 15

### CODE REVIEW

**Comment by EliseAndresen** [comment]
User with no tax unit and only donation in 2018 gives error when entering Årsoppgave page

image

**Comment by EliseAndresen** [comment]
Found a user who still gets warning of donations without tax unit, but the sum is 0. They have several facebook donations for that year, so that could be the reason?

**Comment by fellmirr** [comment]
> User with no tax unit and only donation in 2018 gives error when entering Årsoppgave page
> 
> image

Fixed 👍

**Comment by fellmirr** [comment]
> Found a user who still gets warning of donations without tax unit, but the sum is 0. They have several facebook donations for that year, so that could be the reason?

Also fixed 👍

**Review by EliseAndresen — COMMENTED** [review]
👍

**Review by EliseAndresen — APPROVED** [review]

**Comment by EliseAndresen** [comment]
Getting o.map is not a function error for user without donations for 2022 again

**Pull request merged**
