### PR TITLE
Generic topplista page

### LINKED ISSUE #669: [Feature]: Make topplista page generic
### Contact Details

_No response_

### Description

In the general effort to migrate from custom pages, migrate custom "topplista" page to use generic page instead.

- [x] #670

### Link to figma / design node

_No response_

### Link to other planning document

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by adamalfredsson**
Make topplista page generic

- closes #669 

---

Tested on devices

- [x] Desktop 💻
- [x] Mobile 📱

Tests

- [ ] All tests are running ✔️
- [ ] Test are updated 🧪
- [ ] Code Review 👩‍💻
- [ ] QA 👌

⏲️ Time spent on CR:

⏲️ Time spent on QA:

### CODE REVIEW

**Comment by adamalfredsson** [comment]
This should be ready to merge now! I've added a custom page to each dataset with the same data as contained in the custom page.

**Comment by adamalfredsson** [comment]
I'm thinking we'll remove the organizations custom page schema after this is merged. I've added a separate issue for this #674

**Comment by fellmirr** [comment]
@adam Seems to be a conflict with [slug] now, probably because I merged some of your filtering logic :)

**Review by fellmirr — APPROVED** [review]
Other than the conflict, this looks excellent :)

**Pull request merged**
