### PR TITLE
Dynamic articles page route

### LINKED ISSUE #693: [Feature]: Dynamic articles route
### Contact Details

_No response_

### Description

For #692 we need to use a dynamic route for the articles page

### Link to figma / design node

_No response_

### Link to other planning document

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by adamalfredsson**
- closes #693 

- Adds a page extension for routes within the `pages/` directory
- The "catch-all" route renders generic page or articles page dynamically

---

Tested on devices

- [ ] Desktop 💻
- [ ] Mobile 📱

Tests

- [ ] All tests are running ✔️
- [ ] Test are updated 🧪
- [ ] Code Review 👩‍💻
- [ ] QA 👌

⏲️ Time spent on CR:

⏲️ Time spent on QA:

### CODE REVIEW

**Comment by fellmirr** [comment]
@adamalfredsson This looks solid. I really like the `.page` convention :D Is it dependent on another change, or is it ready to be merged?

**Comment by adamalfredsson** [comment]
> @adamalfredsson This looks solid. I really like the `.page` convention :D Is it dependent on another change, or is it ready to be merged?

Thanks! This should be ready without any dependencies!

**Comment by fellmirr** [comment]
@adamalfredsson Looks perfect as far as I can tell :)

**Review by fellmirr — APPROVED** [review]
👍

**Comment by adamalfredsson** [comment]
Seems so! Let's merge 🙏

**Pull request merged**
